Repository outwatch/outwatch, pull requests merged in 2023-11, with the labels that each got.

#746 update colibri
  build.sbt
  outwatch/src/main/scala/outwatch/EmitterBuilder.scala
  tests/src/test/scala/outwatch/OutWatchDomSpec.scala
Labels: publish, ready-to-merge-squash

#751 fix undefined value not propagating in EmitterBuilder combine
  outwatch/src/main/scala/outwatch/EmitterBuilder.scala
Labels: ready-to-merge-squash

#752 Update colibri, colibri-jsdom, ... to 0.8.1
  build.sbt
Labels: dependencies, scala

#753 Update scalafmt-core to 3.7.17
  .scalafmt.conf
Labels: dependencies, scala
